# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='', max_length=255, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=255, verbose_name='Surname'),
        ),
    ]
