# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('charity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('registered_number', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Registered number')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name=b'Short description')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name=b'Long description')),
                ('enabled', models.BooleanField(default=False, verbose_name=b'Enabled')),
                ('website_url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Website URL')),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Logo URL')),
                ('cover_image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Cover image URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name=b'Order')),
                ('race_years', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Race years')),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Facebook URL')),
                ('twitter_url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Twitter URL')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Charities',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, verbose_name=b'Question')),
                ('answer', models.CharField(max_length=255, verbose_name=b'Answer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name=b'Order')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('marketing_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=255, verbose_name=b'Email address')),
                ('enabled', models.BooleanField(default=False, verbose_name=b'Enabled')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingSource',
            fields=[
                ('marketingsource_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('enabled', models.BooleanField(default=False, verbose_name=b'Enabled')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NVP',
            fields=[
                ('nvp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('value', models.CharField(max_length=255, verbose_name=b'Value')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_pre_string', models.CharField(max_length=255, verbose_name=b'URL pre-string')),
                ('filename', models.CharField(max_length=100, verbose_name=b'Filename')),
                ('extension', models.CharField(max_length=4, verbose_name=b'File extensions')),
                ('race_year', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=b'Race year')),
                ('entrant_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=b'Entrant number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0, verbose_name=b'Position')),
                ('entrant_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=b'Entrant number')),
                ('firstname', models.CharField(max_length=255, verbose_name=b'Firstname')),
                ('surname', models.CharField(max_length=255, verbose_name=b'Surname')),
                ('team_name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Team name')),
                ('registration_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=b'Registration number')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Category')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Gender')),
                ('date_of_birth', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Date of birth')),
                ('no_mail', models.BooleanField(default=False, verbose_name=b'No mail')),
                ('finish_time', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Finish time')),
                ('chip_time', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Chip time')),
                ('split_time', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Split time')),
                ('performance_grading', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name=b'Performance grading')),
                ('race_year', models.PositiveIntegerField(default=0, verbose_name=b'Race year')),
                ('race_type', models.CharField(max_length=10, verbose_name=b'Race type')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunningClub',
            fields=[
                ('runningclub_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('website_url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Website URL')),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Logo URL')),
                ('enabled', models.BooleanField(default=False, verbose_name=b'Enabled')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('description', models.TextField(verbose_name=b'Description')),
                ('enabled', models.BooleanField(default=False, verbose_name=b'Enabled')),
                ('website_url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Website URL')),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Logo URL')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000, verbose_name=b'Message')),
                ('previous_name', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Previous name')),
                ('race_year', models.PositiveIntegerField(default=0, verbose_name=b'Race year')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userprofile_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name=b'Gender')),
                ('terms_agreed', models.DateTimeField(verbose_name=b'Terms agreed')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('marketingsource_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.MarketingSource')),
            ],
        ),
    ]
