# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_photo_race_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='race_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Race'),
        ),
    ]
