# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180119_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'imageuploads'),
        ),
    ]
