# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_charity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='image',
        ),
        migrations.AddField(
            model_name='charity',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to=b'admin_file_uploads'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='cover_image_url',
            field=models.ImageField(blank=True, null=True, upload_to=b'admin_file_uploads'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to=b'admin_file_uploads'),
        ),
    ]
