# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180121_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='amount_raised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Amount raised'),
        ),
    ]
