# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_charity_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity_profile',
            old_name='race_years',
            new_name='race_year',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='amount_raised',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='order',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='race_years',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='charity_profile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='charity_profile',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='charity_profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='charity_profile',
            name='order',
        ),
        migrations.RemoveField(
            model_name='charity_profile',
            name='registered_number',
        ),
        migrations.RemoveField(
            model_name='charity_profile',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='charity_profile',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='charity_profile',
            name='charity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Charity'),
        ),
        migrations.AddField(
            model_name='charity_profile',
            name='charity_profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        )

    ]
