# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180122_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityProfile',
            fields=[
                ('charity_profile_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('short_description', models.TextField(blank=True, null=True, verbose_name=b'Short description')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name=b'Long description')),
                ('enabled', models.BooleanField(default=False, verbose_name=b'Enabled')),
                ('cover_image_url', models.ImageField(blank=True, null=True, upload_to=b'admin_file_uploads')),
                ('video_url', models.FileField(blank=True, null=True, upload_to=b'admin_file_uploads')),
                ('race_year', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Race years')),
                ('amount_raised', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Amount raised')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('charity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Charity')),
            ],
            options={
                'verbose_name_plural': 'Charity Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='charity_profile',
            name='charity_id',
        ),
        migrations.DeleteModel(
            name='Charity_Profile',
        ),
    ]
