# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180122_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityprofile',
            name='race_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Race year'),
        ),
    ]
