# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180122_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityprofile',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
