# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180123_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcategory',
            options={'verbose_name_plural': 'Contact Categories'},
        ),
    ]
