# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180123_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Address'),
        ),
    ]
