# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=1000, verbose_name=b'Answer'),
        ),
    ]
