# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_sponsorprofile_sponsorship_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorprofile',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to=b'images/'),
        ),
    ]
