# Generated by Django 2.1.1 on 2019-10-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20180928_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorprofile',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
