# Generated by Django 2.2.6 on 2019-11-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20191008_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingsource',
            old_name='marketingsource_id',
            new_name='marketing_source_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='marketingsource_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marketing_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.MarketingSource', to_field='marketing_source_id'),
        ),
    ]
